### PR TITLE
Add support for avatar rewards ( + fix date overlapping with title)

### LINKED ISSUE #200: Reward notification date overlaps with reward title
image

### PR DESCRIPTION
**Pull request by An0n3m0us**
Closes #200 

image

- [x] Fix date overlapping with title
- [x] Add support for avatar rewards (thumbnail, content)
- [x] Fix URL for avatar rewards (uses `me` instead of `KAID` or `username` which interrupts redirect)

### CODE REVIEW

**Review by JettBurns14 — CHANGES_REQUESTED** [review]
This is... odd. Not sure why this code would cause text overlap. It simply checks if notif.content exists, and adds the content if so. I noticed in the notif interface that [notif.content is optional](https://github.com/ka-extension/ka-extension-ts/blob/b53a4e7c76fa3d05ad95e4e71837ce420c422328/src/types/data.ts#L92), so this check makes sense to have in case it's not there.

Could you include screenshots/pasted HTML from the popup notifications before and after this fix? Also, could you check if these notifications have content values or not in the API request the extension sends? That'll give me more context.

File: src/popup.ts [hunk 1]
```diff
@@ -117,7 +117,7 @@ function genNotif (notif: NotifElm): string {
 				<div class="notif-wrap">
 					<img class="notif-img" src="${notif.imgSrc}">
 					<p class="author-note">${notif.authorNote}</p>
-					${notif.content && `<p class="notif-content">${notif.content}</p>`}
```
Comment (JettBurns14) [inline src/popup.ts:120]: This is... odd. Not sure why this code would cause text overlap. It simply checks if notif.content exists, and adds the content if so. I noticed in the Notification interface that [notif.content is optional](https://github.com/ka-extension/ka-extension-ts/blob/b53a4e7c76fa3d05ad95e4e71837ce420c422328/src/types/data.ts#L92), so this check makes sense to have in case it's not there, and I'm not quite convinced on removing it.

Comment (An0n3m0us) [reply src/popup.ts:120]: I _think_ it's to do with the margin stuff, and since I've made it so that the <p> tag exists whatever the case, the margin is kept.
I'm really new to all this code so I don't quite know what I'm doing yet xD

**Comment by An0n3m0us** [comment]
> Could you include screenshots/pasted HTML from the popup notifications before and after this fix? Also, could you check if these notifications have content values or not in the API request the extension sends? That'll give me more context.

Oh, you're completely correct; I forgot to test this without the extension.
I'll try and continue work on this soon.

File: src/popup.ts (hunk 1 above)
Comment (An0n3m0us) [reply src/popup.ts:120]: But since these types of notifications have content anyway, I'll probably revert this change.

Comment (JettBurns14) [reply src/popup.ts:120]: Ah, I think you're correct, the `notif-content` class gives it left padding of 50px, [seen here](https://github.com/ka-extension/ka-extension-ts/blob/b53a4e7c76fa3d05ad95e4e71837ce420c422328/popup/popup.css#L131). Doesn't seem like a good way to pad something TBH, evidenced by this overlap bug, lol.

And hey, no problem, I appreciate you working on stuff!

**Comment by JettBurns14** [comment]
I'll see about getting my local extension running again and testing your fix, and possibly adding my own. I'll probably be on the KAE Discord tomorrow if you want to talk details there. Thanks for contributing!

File: src/popup.ts (hunk 1 above)
Comment (An0n3m0us) [reply src/popup.ts]: For avatar rewards, there is a different API entry for the content text, so all I had to do is set it to that.

image

So I've kept the code above that I removed before.

**Comment by An0n3m0us** [comment]
> Could you include screenshots/pasted HTML from the popup notifications before and after this fix?

I couldn't work out how to do it first, but here it is xD

CURRENT <--- ---> NEW
image

(This is for the two badges shown in the screenshot in the original post)

**Comment by An0n3m0us** [comment]
There is a small issue;
The URL needs to be modified for the rewards notification.

Lets take the Hopper reward notification shown in the original post.
In the API entry, the URL is like this:
`/profile/me?show_avatar_customizer=1&selected_avatar_part=hopper_jumping_style`

But using `/me` does not seem to redirect to the badge as it's busy redirecting to the users profile.
So the original redirect is ignored.

Instead, using either the KAID or username will work.
Code for this should be added to the `href` item in the `NotifElm` object.

**Comment by An0n3m0us** [comment]
I have managed to fix it now, but I got this error on the first build:
```
ERROR in ./src/popup.ts
./src/popup.ts
[tsl] ERROR in ./src/popup.ts(139,97)
      TS2532: Object is possibly 'undefined'.
```

But after running the build command again the error does not show.
So is the error existent or not?

**Comment by JettBurns14** [comment]
Very cool! I won't be on Discord today after all, got busy, but likely will tomorrow, and will see about testing this change then.

**Comment by An0n3m0us** [comment]
No problem! I would not be available anyway as Europe is 7-8 hours ahead of Central Time.
But if there are any details I need information on, I guess I can just post in DM/general chat and await your reply.

**Comment by An0n3m0us** [comment]
> Could you include screenshots/pasted HTML from the popup notifications before and after this fix? 

https://github.com/ka-extension/ka-extension-ts/pull/201#issuecomment-790372264

> Also, could you check if these notifications have content values or not in the API request the extension sends?

It seems not. Here's the API entries for the notifications that I have shown in the original post:
https://www.dropbox.com/s/jjwog2mkl53kkhx/notifications.json?dl=0

**Comment by JettBurns14** [comment]
@An0n3m0us Looks good to me. It'd probably be easier if I merge this before #211, then you update that branch accordingly.

File: src/types/data.ts [hunk 2]
```diff
@@ -104,6 +104,7 @@ interface Notification {
 	focusTitle?: string;
 	kaid?: string;
 	kind: string;
+	name: string;
```
Comment (JettBurns14) [inline src/types/data.ts:107]: This key isn't always available for every notification, so let's use `name?:` instead here. Same for `translatedRequirements` below. After that, I'll merge.

**Review by JettBurns14 — CHANGES_REQUESTED** [review]

File: src/types/data.ts (hunk 2 above)
Comment (An0n3m0us) [reply src/types/data.ts]: Okay, done

**Review by MatthiasSaihttam — APPROVED** [review]
